// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Dropdown$ReasonmlDropdownMenuTutorial from "./DropDownMenu/Dropdown.js";

import './App.css'
;

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, React.createElement("div", {
                  style: {
                    display: "flex",
                    justifyContent: "center"
                  }
                }, React.createElement(Dropdown$ReasonmlDropdownMenuTutorial.make, { })));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
