// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Dropdown$ReasonmlDropdownMenuTutorial from "./DropDownMenu/Dropdown.bs.js";

import './App.css'
;

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, React.createElement("header", {
                  className: "App-header"
                }, React.createElement("a", {
                      className: "App-link",
                      href: "https://github.com/idkjs/reasonml-dropdown-menu-tutorial",
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, "ReasonML Dropdown Menu Tutorial(Click to see the source code)")), React.createElement("div", {
                  style: {
                    display: "flex",
                    justifyContent: "center"
                  }
                }, React.createElement(Dropdown$ReasonmlDropdownMenuTutorial.make, {})));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
